# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae2c7180759c41e7adee3185e8f55b18ff1712640752ee3fe04b4e58216040cb2fa7f9880e0bfa8f8c6203a9678d96829bfd7b44a27aaa6e9ad8742461c61a6

test:
  secret_key_base: b34770511f5b8404dae930e28b68743db76e4e3ca437bf50d1a4e55c7ae8157641535da456587811a42a9566ec2952e546d2204ab370c90f88976c84ab42e132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
